server:
  port: 8888
spring:
  profiles:
    active: mysql
  jackson:
    default-property-inclusion: NON_EMPTY
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss]
  jpa:
    dashow-sql: true
  thymeleaf:
    cache: false
  mail:
    host: smtp.qq.com
    username: yqzhu1528@foxmail.com
    #发送方的授权码
    password: xbrogbbyqnotbfje
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: ture
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

logging:
  level:
    root: ERROR
    org:
      springframework: ERROR
    # SQL 的日志输出级别为 DEBUG
    io:
      walkers: DEBUG

# MyBatis 下划线命名转驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

fund:
  datasource:
    valuePath: https://stock.finance.sina.com.cn/fundInfo/api/openapi.php/CaihuiFundInfoService.getNav
    detailPathPrefix: http://fund.eastmoney.com/
    detailPathSuffix: .html