spring:
  # 配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fundhelper?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    # 用户名要修改为自己的用户名
    username: root
    password: password